# 直线识别参数
LineDetector:
  Min_val: 120
  Max_val: 255
  Hough_threshold: 48
  minLineLength: 70
  maxLineGap: 49
  bias: 1
  sigma: 0
  odd_index: 3

# 位号顶点
area1_points:
  - [25, 0]
  - [168, 118]
area2_points:
  - [168, 0]
  - [293, 118]
area3_points:
  - [65, 118]
  - [290, 237]

# 颜色阈值
color:
  R:
    centre: 0
    error: 17
    L_S: 80
    U_S: 255
    L_V: 40
    U_V: 255

  G:
    centre: 65
    error: 20
    L_S: 80
    U_S: 255
    L_V: 40
    U_V: 255

  B:
    centre: 109
    error: 17
    L_S: 80
    U_S: 255
    L_V: 40
    U_V: 255

# 目标面积
min_material_area: 2000
max_material_area: 40000

# 霍斯圆参数
annulus:
    dp: 1
    minDist: 100
    param1: 100
    param2: 100
    minRadius: 40
    maxRadius: 97
    sigma: 0
    odd_index: 3

# 目标角度
target_angle: 46

# 画面底部需要被裁剪的高度
need2cut_height: 20
