LineDetector:
  H_High: 57
  H_Low: 12
  Hough_threshold: 30
  Max_val: 21
  Min_val: 0
  S_High: 200
  S_Low: 5
  V_High: 240
  V_Low: 0
  bias: 4
  iter_time: 1
  maxLineGap: 49
  minLineLength: 60
  odd_index: 6
  sigma: 2.4
annulus:
  dp: 1
  iter_time: 5
  maxRadius: 78
  minDist: 100
  minRadius: 47
  odd_index: 2
  param1: 85
  param2: 12
  sigma: 0.0
area1_points:
- - 25
  - 0
- - 168
  - 118
area2_points:
- - 168
  - 0
- - 360
  - 118
area3_points:
- - 25
  - 118
- - 360
  - 237
clientsIp_debug:
- 169.254.255.255
color:
  B:
    L_S: 80
    L_V: 20
    U_S: 255
    U_V: 255
    centre: 109
    error: 17
  G:
    L_S: 80
    L_V: 20
    U_S: 255
    U_V: 255
    centre: 65
    error: 17
  R:
    L_S: 80
    L_V: 20
    U_S: 255
    U_V: 255
    centre: 0
    error: 17
max_material_area: 26000
min_material_area: 300
need2cut_height: 0
target_angle: 46
