LineDetector:
  Hough_threshold: 10
  Max_val: 255
  Min_val: 76
  bias: 1
  maxLineGap: 49
  minLineLength: 0
  odd_index: 2
  sigma: 0.0
annulus:
  dp: 1
  maxRadius: 97
  minDist: 100
  minRadius: 40
  odd_index: 2
  param1: 100
  param2: 100
  sigma: 0.0
area1_points:
  - [25, 0]
  - [168, 118]
area2_points:
  - [168, 0]
  - [293, 118]
area3_points:
  - [65, 118]
  - [290, 237]

# 颜色阈值
color:
  B:
    L_S: 80
    L_V: 40
    U_S: 255
    U_V: 255
    centre: 109
    error: 17
  G:
    L_S: 80
    L_V: 40
    U_S: 255
    U_V: 255
    centre: 65
    error: 20
  R:
    L_S: 80
    L_V: 40
    U_S: 255
    U_V: 255
    centre: 0
    error: 17
max_material_area: 40000
min_material_area: 2000
need2cut_height: 80
target_angle: 46
