LineDetector:
  Hough_threshold: 10
  Max_val: 154
  Min_val: 33
  bias: 1
  iter_time: 4
  maxLineGap: 49
  minLineLength: 0
  odd_index: 2
  sigma: 0.0
annulus:
  dp: 1
  iter_time: 7
  maxRadius: 46
  minDist: 100
  minRadius: 11
  odd_index: 2
  param1: 100
  param2: 14
  sigma: 0.0
area1_points:
- - 25
  - 0
- - 168
  - 118
area2_points:
- - 168
  - 0
- - 360
  - 118
area3_points:
- - 25
  - 118
- - 360
  - 237
clientsIp:
- 169.254.233.52
color:
  B:
    L_S: 80
    L_V: 20
    U_S: 255
    U_V: 255
    centre: 109
    error: 17
  G:
    L_S: 80
    L_V: 20
    U_S: 255
    U_V: 255
    centre: 65
    error: 17
  R:
    L_S: 80
    L_V: 20
    U_S: 255
    U_V: 255
    centre: 0
    error: 17
max_material_area: 26000
min_material_area: 0
need2cut_height: 0
target_angle: 46
